name: utils
version: 0.84
date: 2023-09-11
description: |
    Utility functions in GAP

authors:
    - name: Thomas Breuer
      url: https://www.math.rwth-aachen.de/~Thomas.Breuer
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io/
    - name: Max Horn
      url: https://github.com/mhorn
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke
    - name: Pedro García-Sánchez
      url: http://www.ugr.es/local/pedro
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk/
    - name: Stefan Kohl
      url: https://www.gap-system.org/DevelopersPages/StefanKohl/
    - name: Frank Lübeck
      url: https://www.math.rwth-aachen.de/~Frank.Luebeck
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.10.1"

suggested-pkgs:
    - name: "curlInterface"
      version: ">= 2.3.0"
      url: "https://gap-packages.github.io/curlInterface/"

www: https://gap-packages.github.io/utils
readme: README.md
packageinfo: https://gap-packages.github.io/utils/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/utils/releases/download/v0.84/utils-0.84.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/utils/releases/download/v0.84/utils-0.84.zip

abstract: |
    The <span class="pkgname">Utils</span> package provides a collection   of utility functions gleaned from many packages.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
