name: utils
version: 0.74
date: 2022-07-09
description: |
    Utility functions in GAP

authors:
    - name: Thomas Breuer
      url: https://www.math.rwth-aachen.de/~Thomas.Breuer
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io/
    - name: Max Horn
      url: https://github.com/mhorn
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke
    - name: Stefan Kohl
      url: https://www.gap-system.org/DevelopersPages/StefanKohl/
    - name: Frank Lübeck
      url: https://www.math.rwth-aachen.de/~Frank.Luebeck
    - name: Chris Wensley
      url: https://github.com/cdwensley

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.10.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2020.08.11"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "GAPDoc"
      version: ">= 1.6.4"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "polycyclic"
      version: ">= 2.16"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/utils
readme: README.md
packageinfo: https://gap-packages.github.io/utils/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/utils/releases/download/v0.74/utils-0.74.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/utils/releases/download/v0.74/utils-0.74.zip

abstract: |
    The <span class="pkgname">Utils</span> package provides a collection   of utility functions gleaned from many packages.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
